Update PR-708.yml

diff --git a/.github/workflows/PR-708.yml b/.github/workflows/PR-708.yml
--- a/.github/workflows/PR-708.yml
+++ b/.github/workflows/PR-708.yml
@@ -12,6 +12,12 @@ jobs:
         # python-version: ['3.10', '3.12']
         python-version: ['3.9']
     steps:
+      - name: Ensure Sudo is Installed
+        run: |
+          if ! command -v sudo &> /dev/null; then
+            echo "sudo could not be found. Installing..."
+            sudo apt-get update && sudo apt-get install -y sudo
+          fi
       - name: Checkout repository
         uses: actions/checkout@v4
       - name: Set up Python
